### ISSUE TITLE
When adding new Fruit: "bad request"

### ISSUE THREAD

**Issue by ALRubinger** [bucharest-gold/nodejs-rest-http-crud#39]
To replicate:

Launch on Minishift a new CRUD Node Booster
Wait for deployment
Navigate to index.html in the route
Use the form to create a new fruit name and qualtity
Hit "save"
See "bad request" response returned as dialog box in Chrome, for instance

**Comment by lholmquist** [comment]
@ALRubinger i'll check it out.   is the database up when you run this command?

is there also anything in the pod log?

**Comment by lholmquist** [comment]
I just tried with what is in master,  I get the bad request error, but that is only because i didn't create the database first.

Once i run `oc new-app -e POSTGRESQL_USER=luke -ePOSTGRESQL_PASSWORD=secret -ePOSTGRESQL_DATABASE=my_data openshift/postgresql-92-centos7 --name=my-database` 

then redeploy my app and refresh the page,  everything works
